# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0007_auto_20170605_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeinfo',
            name='prev_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tradeinfo_prev_club', to='introduction_to_models.Club'),
        ),
        migrations.AddField(
            model_name='tradeinfo',
            name='recommender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tradeinfo_recommender', to='introduction_to_models.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
